name       : mtpfs
version    : 1.1
release    : 2
source     :
    - http://www.adebenham.com/files/mtp/mtpfs-1.1.tar.gz : 1baf357de16995a5f0b5bc1b6833517a77456481d861cdba70f1ce1316ce4c1d
license    : GPL-3.0
summary    : MTPFS is a FUSE filesystem based on libmtp that allows a mtp device to be browsed as if it were a normal external harddisk.
description: |
    MTPFS is a FUSE filesystem based on libmtp that allows a mtp device to be browsed as if it were a normal external harddisk.
builddeps  :
    - pkgconfig(fuse)
    - pkgconfig(libmtp)
    - pkgconfig(glib-2.0)
setup      : |
    %configure --disable-mad
build      : |
    %make
install    : |
    %make_install
